// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://empbhepumsgvvomqbbyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcGJoZXB1bXNndnZvbXFiYnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTcwMjUsImV4cCI6MjA2MzczMzAyNX0.yWCw9-C0FBLTpt3WMcH1Luo3cOs-Sp4VfXQT3gQPtVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});