// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zdqkrrehlivayconjcgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcWtycmVobGl2YXljb25qY2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjAxNjQsImV4cCI6MjA2NTQzNjE2NH0.ZEwZo8TNkaWP0SxVmfXCx2zQt5sdIwWXiy9US4E2i1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});